[package]
name = "crates"
version = "0.1.0"
authors = ["csruiliu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[[example]]
name = "consume_crates"
path = "src/consume_crates.rs"